// A subset of top Indian/Global medicines for the autocomplete dropdown.
// In a full production app, this could be loaded dynamically or expanded.

export const COMMON_MEDICINES = [
  "Aspirin",
  "Dolo 650",
  "Paracetamol",
  "Crocin",
  "Calpol",
  "Pantocid",
  "Allegra",
  "Ecosprin",
  "Lisinopril",
  "Atorvastatin",
  "Metformin",
  "Amlodipine",
  "Thyronorm",
  "Shelcal",
  "Levocetirizine",
  "Montelukast",
  "Azithromycin",
  "Amoxicillin",
  "Omeprazole",
  "Telmisartan",
  "Losartan",
  "Metoprolol",
  "Rosuvastatin",
  "Pantoprazole",
  "Diclofenac",
  "Ibuprofen",
  "Cetirizine",
  "Domperidone",
  "Ondansetron",
  "Ranitidine",
  "Clopidogrel",
  "Glimepiride",
  "Gliclazide",
  "Vildagliptin",
  "Sitagliptin",
  "Dapagliflozin"
];
